"""
scripts/merge_recovered_leads.py
--------------------------------
Write the leads recovered by recover_article_leads.py back into the audited
dataset, with provenance.

Stage 1 of the audit correctly cleared 764 Google-RSS wrapper "leads" that held
markup rather than article text, which left 278 of 371 rows title-only.
recover_article_leads.py refetched the real text; this merges it in.

`lead_source` records where each lead came from, so the thesis can state the
provenance mix exactly:
    original_fetch  - lead survived the original collection
    publisher_url   - refetched from the publisher (audit stage 1)
    recovered_publisher - refetched here via Google News token resolution
    recovered_wayback   - recovered here from a Wayback snapshot
    (empty)         - still no lead; article is title-only

NOTE: the dataset parquet is generated by audit_stage2_rebuild.py. Re-running
the audit will overwrite this merge unless the recovery step is wired into
stage 2. Rerun this script after any audit rebuild.
"""
from __future__ import annotations

import logging
import shutil
from datetime import datetime
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("merge_leads")

DATASET = Path("data/processed/calabarzon_food_insecurity_dataset.parquet")
DATASET_CSV = Path("data/processed/calabarzon_food_insecurity_dataset.csv")
RECOVERED = Path("data/processed/_recovered_leads.parquet")
ARCHIVE = Path("data/archive/pre_lead_merge")
MIN_LEAD = 80


def main() -> None:
    df = pd.read_parquet(DATASET)
    rec = pd.read_parquet(RECOVERED)
    good = rec[rec["lead_chars"] >= MIN_LEAD].drop_duplicates("article_id")
    log.info("dataset %d rows | recovered leads available: %d", len(df), len(good))

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    ARCHIVE.mkdir(parents=True, exist_ok=True)
    shutil.copy2(DATASET, ARCHIVE / f"dataset_{stamp}.parquet")
    log.info("backed up -> %s", ARCHIVE / f"dataset_{stamp}.parquet")

    df["content_lead"] = df["content_lead"].fillna("").astype(str)
    df["lead_source"] = df["lead_source"].fillna("").astype(str)
    before_empty = int((df["content_lead"].str.len() == 0).sum())

    lead_map = dict(zip(good["article_id"], good["lead"]))
    path_map = dict(zip(good["article_id"], good["recovery_path"]))
    url_map = dict(zip(good["article_id"], good["resolved_url"]))

    filled = 0
    for i, r in df.iterrows():
        aid = r["article_id"]
        if len(r["content_lead"]) == 0 and aid in lead_map:
            df.at[i, "content_lead"] = lead_map[aid]
            df.at[i, "lead_source"] = "recovered_" + str(path_map.get(aid, "publisher"))
            filled += 1

    # Keep the publisher URL the token resolved to - the google news redirect is
    # not a citable source for a thesis bibliography.
    if "resolved_url" not in df.columns:
        df["resolved_url"] = ""
    df["resolved_url"] = df.apply(
        lambda r: url_map.get(r["article_id"], r.get("resolved_url") or ""), axis=1
    )

    after_empty = int((df["content_lead"].str.len() == 0).sum())
    log.info("leads filled: %d | title-only before: %d -> after: %d",
             filled, before_empty, after_empty)

    df.to_parquet(DATASET, index=False)
    try:
        df.to_csv(DATASET_CSV, index=False, encoding="utf-8")
    except PermissionError:
        alt = DATASET_CSV.with_suffix(".locked.csv")
        df.to_csv(alt, index=False, encoding="utf-8")
        log.warning("csv locked (Excel?) - wrote %s instead", alt)

    log.info("lead_source mix: %s", dict(df["lead_source"].replace("", "(none)").value_counts()))
    log.info("lead length: median %d, mean %.0f",
             int(df["content_lead"].str.len().median()),
             df["content_lead"].str.len().mean())
    log.info("saved -> %s", DATASET)


if __name__ == "__main__":
    main()
