"""
app/ml/corpus/lgu_census_fetcher.py
------------------------------------
PSA 2020 Census of Population and Housing (CPH 2020) — LGU population +
land area + density fetcher for CALABARZON.

PURPOSE
-------
Provides the **density component** of the municipal disaggregation formula:
    y_m = y_province × (0.6 × poverty_m + 0.4 × density_m)

Population: PSA 2020 CPH official totals.
Land area: PSA / DILG Local Government Profiles (km²).
Density:   population / land_area (persons/km²).

DATA STRATEGY
-------------
Population for all CALABARZON LGUs (142 cities + municipalities) is sourced
from PSA's published 2020 CPH municipal totals. Land area is from PSA
Philippine Statistical Yearbook municipal land area table (also published
in DILG LGU profiles). Both are public, primary government statistics.

The canonical 142-LGU roster lives in data/reference/calabarzon_lgus.csv,
generated by scripts/build_lgu_reference.py from the PSGC gazetteer so that
LGU identity (code, official name, city/municipality class) has exactly one
source of truth. If that CSV is missing, this module falls back to the
CURATED_LGUS subset below and logs a warning; if it is present but short of
142 rows, the build fails loudly.

OUTPUT
------
data/processed/lgu_census.parquet — columns:
    province_code     : str (PSGC)
    province_name     : str
    lgu_code          : str (PSGC 9-digit)
    lgu_name          : str (PSGC-canonical spelling)
    lgu_aliases       : str (pipe-separated alternate spellings, may be empty)
    lgu_type          : str ("city" | "municipality")
    population_2020   : int
    land_area_km2     : float
    density_per_km2   : float
    population_source : str ("cph2020" exact PSA total | "estimate" rounded)
    density_normalized: float (0-1, min-max within province — for disaggregator)
    source_url        : str
    fetched_at        : str

TRAINING WINDOW: 2020-2025. CPH 2020 anchors the entire window
(population is treated as static across the 6-year horizon, standard
practice in food-security disaggregation models).
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)

OUTPUT_PATH = Path("data/processed/lgu_census.parquet")
REFERENCE_DIR = Path("data/reference")

# Region IV-A has exactly 142 cities/municipalities:
#   Batangas 34 · Cavite 23 · Laguna 30 · Quezon 41 · Rizal 14
EXPECTED_LGU_COUNT = 142

PROVINCE_MAP = {
    "PH040100000": "Cavite",
    "PH040200000": "Laguna",
    "PH040300000": "Quezon",
    "PH040400000": "Rizal",
    "PH040500000": "Batangas",
}

# Primary citation for all CPH 2020 figures
SOURCE_URL = "https://psa.gov.ph/population-and-housing/2020-CPH"

# ---------------------------------------------------------------------------
# CALABARZON LGU population — PSA 2020 CPH (curated; 142 LGUs)
# Each row: (province_code, lgu_name, lgu_type, population_2020, land_area_km2)
# Population: PSA 2020 CPH municipal totals.
# Land area: PSA Statistical Yearbook 2022 / DILG LGU Profiles.
# ---------------------------------------------------------------------------
# Below is a representative set covering the largest LGUs per province for
# disaggregation. The fetcher loads a full CSV from data/reference/ if
# present (preferred) and falls back to this curated subset otherwise.

CURATED_LGUS: list[tuple] = [
    # Cavite (key cities + municipalities)
    ("PH040100000", "Bacoor", "city", 664625, 46.17),
    ("PH040100000", "Imus", "city", 496794, 53.15),
    ("PH040100000", "Dasmariñas", "city", 703141, 90.10),
    ("PH040100000", "General Trias", "city", 450583, 84.46),
    ("PH040100000", "Trece Martires", "city", 210503, 78.60),
    ("PH040100000", "Tagaytay", "city", 85330, 65.00),
    ("PH040100000", "Cavite City", "city", 100674, 11.79),
    ("PH040100000", "Silang", "municipality", 295644, 156.41),
    ("PH040100000", "Carmona", "city", 106256, 30.92),
    ("PH040100000", "Kawit", "municipality", 107535, 13.40),
    # Laguna (key cities + municipalities)
    ("PH040200000", "Calamba", "city", 539671, 149.50),
    ("PH040200000", "San Pedro", "city", 326001, 24.05),
    ("PH040200000", "Biñan", "city", 407437, 43.50),
    ("PH040200000", "Santa Rosa", "city", 414812, 54.13),
    ("PH040200000", "Cabuyao", "city", 355330, 43.40),
    ("PH040200000", "San Pablo", "city", 285348, 197.56),
    ("PH040200000", "Los Baños", "municipality", 115353, 56.74),
    ("PH040200000", "Bay", "municipality", 64200, 42.66),
    # Quezon (key LGUs — largest province by area in CALABARZON)
    ("PH040300000", "Lucena", "city", 278924, 71.55),
    ("PH040300000", "Tayabas", "city", 112658, 230.95),
    ("PH040300000", "Sariaya", "municipality", 162717, 245.30),
    ("PH040300000", "Candelaria", "municipality", 130172, 167.80),
    ("PH040300000", "Tiaong", "municipality", 100404, 124.18),
    # Rizal
    ("PH040400000", "Antipolo", "city", 887399, 306.10),
    ("PH040400000", "Cainta", "municipality", 376933, 42.99),
    ("PH040400000", "Taytay", "municipality", 386451, 38.80),
    ("PH040400000", "Rodriguez", "municipality", 443954, 312.70),
    ("PH040400000", "San Mateo", "municipality", 273063, 55.09),
    # Batangas
    ("PH040500000", "Batangas City", "city", 351437, 282.96),
    ("PH040500000", "Lipa", "city", 372931, 209.40),
    ("PH040500000", "Tanauan", "city", 193936, 107.16),
    ("PH040500000", "Santo Tomas", "city", 218500, 95.41),
    ("PH040500000", "Nasugbu", "municipality", 144490, 278.51),
    ("PH040500000", "Lemery", "municipality", 92682, 105.55),
    ("PH040500000", "Calaca", "city", 96930, 113.78),
]


def _normalize_density(df: pd.DataFrame) -> pd.DataFrame:
    """Min-max normalize density within province (0-1) for disaggregator."""
    df = df.copy()
    df["density_normalized"] = 0.0
    for prov in df["province_code"].unique():
        mask = df["province_code"] == prov
        d = df.loc[mask, "density_per_km2"]
        if d.max() == d.min():
            df.loc[mask, "density_normalized"] = 0.5
        else:
            df.loc[mask, "density_normalized"] = (d - d.min()) / (d.max() - d.min())
    return df


def fetch_lgu_census() -> pd.DataFrame:
    """
    Build LGU population + land area + density panel for CALABARZON.

    Loads the full 142-LGU reference from data/reference/calabarzon_lgus.csv
    (built by scripts/build_lgu_reference.py off the PSGC gazetteer) if present;
    otherwise falls back to the curated subset of major LGUs.

    Raises
    ------
    ValueError
        If the reference CSV is present but does not describe all
        EXPECTED_LGU_COUNT LGUs. A short roster silently starves the
        disaggregator of municipalities, so it is a hard failure rather than a
        warning.
    """
    csv_path = REFERENCE_DIR / "calabarzon_lgus.csv"
    if csv_path.exists():
        logger.info("Loading full LGU set from %s", csv_path)
        # PSGC codes are zero-padded identifiers, not numbers — read them as
        # strings or "041001000" silently becomes 41001000. keep_default_na
        # stops an empty alias cell from turning into the string "nan".
        ref = pd.read_csv(
            csv_path,
            dtype={"lgu_psgc": str, "province_code": str, "lgu_aliases": str},
            keep_default_na=False,
        )
        if len(ref) != EXPECTED_LGU_COUNT:
            raise ValueError(
                f"{csv_path} has {len(ref)} LGUs, expected {EXPECTED_LGU_COUNT}. "
                "Rebuild it with `python scripts/build_lgu_reference.py`."
            )
        rows = ref.to_dict("records")
    else:
        logger.warning("Reference CSV not found at %s — using curated subset (%d of %d LGUs). "
                       "Run `python scripts/build_lgu_reference.py` for the full region.",
                       csv_path, len(CURATED_LGUS), EXPECTED_LGU_COUNT)
        rows = [
            {"province_code": p, "lgu_name": n, "lgu_type": t,
             "population_2020": pop, "land_area_km2": area, "lgu_psgc": ""}
            for p, n, t, pop, area in CURATED_LGUS
        ]

    fetched_at = datetime.now(timezone.utc).isoformat()
    out_rows = []
    for row in rows:
        prov_code = row["province_code"]
        pop, area = int(row["population_2020"]), float(row["land_area_km2"])
        density = pop / area if area > 0 else 0.0
        # Real 9-digit PSGC from the gazetteer. The curated fallback has none,
        # so it keeps a deterministic province-scoped placeholder.
        lgu_code = str(row.get("lgu_psgc") or "").strip()
        if not lgu_code:
            lgu_code = f"{prov_code[:6]}{len(out_rows):03d}000"
        out_rows.append({
            "province_code": prov_code,
            "province_name": PROVINCE_MAP.get(prov_code, ""),
            "lgu_code": lgu_code,
            "lgu_name": row["lgu_name"],
            "lgu_aliases": str(row.get("lgu_aliases") or ""),
            "lgu_type": row["lgu_type"],
            "population_2020": pop,
            "land_area_km2": area,
            "density_per_km2": float(density),
            "population_source": str(row.get("pop_source") or "cph2020"),
            "source_url": SOURCE_URL,
            "fetched_at": fetched_at,
        })

    df = pd.DataFrame(out_rows)
    df = _normalize_density(df)
    logger.info("LGU census: %d LGUs across %d provinces",
                len(df), df["province_code"].nunique())
    return df


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    df = fetch_lgu_census()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(OUTPUT_PATH, index=False)
    print(f"[ok] wrote {OUTPUT_PATH} — {len(df)} rows")
    print(df.head(10).to_string(index=False))


if __name__ == "__main__":
    main()
