"""initial

Revision ID: 63cd1ffe42fe
Revises: 
Create Date: 2026-04-23 19:33:06.572751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cd1ffe42fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('province_code', sa.String(), nullable=False),
    sa.Column('threshold_exceeded', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_quarter_province', 'alert_records', ['quarter', 'province_code'], unique=False)
    op.create_table('forecast_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('province_code', sa.String(), nullable=False),
    sa.Column('province_name', sa.String(), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('risk_label', sa.String(), nullable=False),
    sa.Column('data_sufficiency_flag', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_quarter_province', 'forecast_records', ['quarter', 'province_code'], unique=False)
    op.create_table('shap_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('province_code', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('shap_value', sa.Float(), nullable=False),
    sa.Column('mean_abs_shap', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shap_quarter_province', 'shap_records', ['quarter', 'province_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shap_quarter_province', table_name='shap_records')
    op.drop_table('shap_records')
    op.drop_index('ix_forecast_quarter_province', table_name='forecast_records')
    op.drop_table('forecast_records')
    op.drop_index('ix_alert_quarter_province', table_name='alert_records')
    op.drop_table('alert_records')
    # ### end Alembic commands ###
