"""add municipal forecast records

Revision ID: 68355a016610
Revises: 63cd1ffe42fe
Create Date: 2026-04-29 00:44:57.941210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68355a016610'
down_revision: Union[str, Sequence[str], None] = '63cd1ffe42fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipal_forecast_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('province_code', sa.String(), nullable=False),
    sa.Column('lgu_code', sa.String(), nullable=False),
    sa.Column('municipality_name', sa.String(), nullable=False),
    sa.Column('risk_index', sa.Float(), nullable=False),
    sa.Column('disaggregation_label', sa.String(), nullable=False),
    sa.Column('data_sufficiency_flag', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_municipal_quarter_lgu', 'municipal_forecast_records', ['quarter', 'lgu_code'], unique=False)
    op.create_index('ix_municipal_quarter_province', 'municipal_forecast_records', ['quarter', 'province_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_municipal_quarter_province', table_name='municipal_forecast_records')
    op.drop_index('ix_municipal_quarter_lgu', table_name='municipal_forecast_records')
    op.drop_table('municipal_forecast_records')
    # ### end Alembic commands ###
