"""add admin users, review pipeline, audit and feedback

Revision ID: 809280281fd2
Revises: c3d4e5f6a7b8
Create Date: 2026-09-02 12:40:43.824349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809280281fd2'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('audit_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('province_id', sa.String(), nullable=True),
    sa.Column('quarter', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_timestamp'), 'audit_records', ['timestamp'], unique=False)
    op.create_table('feedback_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('sus_version', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('age_band', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('municipality', sa.String(), nullable=True),
    sa.Column('liked', sa.Text(), nullable=True),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_records_submitted_at'), 'feedback_records', ['submitted_at'], unique=False)
    op.create_table('review_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('province_code', sa.String(), nullable=False),
    sa.Column('province_id', sa.String(), nullable=False),
    sa.Column('province_name', sa.String(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('rejection_notes', sa.Text(), nullable=True),
    sa.Column('generated_on', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_by_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province_id', 'quarter', name='uq_review_province_quarter')
    )
    op.create_index('ix_review_quarter_status', 'review_records', ['quarter', 'status'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index('ix_review_quarter_status', table_name='review_records')
    op.drop_table('review_records')
    op.drop_index(op.f('ix_feedback_records_submitted_at'), table_name='feedback_records')
    op.drop_table('feedback_records')
    op.drop_index(op.f('ix_audit_records_timestamp'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
